---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-engr-backend
  labels:
    # required at namespace creation when hosting a primary UDN
    k8s.ovn.org/primary-user-defined-network: ""
    bewley.net/dept: "engineering"
    bewley.net/team: "backend"
