---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  labels:
    export-as: "65002"
  name: cudn-10-65-0-0-24
spec:
  namespaceSelector:
    matchLabels:
      cudn-10-65-0-0-24: "true"
  network:
    layer2:
      ipam:
        lifecycle: Persistent
      role: Primary
      subnets:
      - 10.65.0.0/24
    topology: Layer2