---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  labels:
    advertise: "true"
    bgp-as: "65002"
    export-as: "65002"
  name: unifi-router
  # must go to this namespace
  namespace: openshift-frr-k8s
spec:
  bgp:
    routers:
    - asn: 65002
      neighbors:
      - address: 192.168.4.1
        asn: 65001
        disableMP: true
        dualStackAddressFamily: false
        toAdvertise:
          allowed:
            mode: all
        toReceive:
          allowed:
            mode: filtered
            prefixes:
              - prefix: 10.254.254.0/24
