---
# This is specific for OCP: v4.21+
apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: default
spec:
  advertisements:
  - PodNetwork
  nodeSelector: {}
  frrConfigurationSelector:
    matchLabels:
      advertise: "true"
  networkSelectors:
  - clusterUserDefinedNetworkSelector:
      networkSelector:
        matchLabels:
          advertise: "true"
    networkSelectionType: ClusterUserDefinedNetworks