!
frr version 10.1.2
frr defaults traditional
hostname UDMPRO
log syslog informational
domainname home.bewley.net
service integrated-vtysh-config
!
ip prefix-list from-ocp-hub seq 5 permit 192.168.179.0/24 le 32
ip prefix-list from-ocp-hub seq 6 permit 10.65.0.0/24 le 32
ip prefix-list to-ocp-hub seq 5 permit 10.254.0.0/16 le 32
!
router bgp 65001
 bgp router-id 192.168.4.1
 bgp log-neighbor-changes
 no bgp enforce-first-as
 no bgp hard-administrative-reset
 no bgp default ipv4-unicast
 no bgp graceful-restart notification
 neighbor ocp-hub peer-group
 neighbor ocp-hub remote-as 65002
 neighbor 192.168.4.44 peer-group ocp-hub
 neighbor 192.168.4.61 peer-group ocp-hub
 neighbor 192.168.4.83 peer-group ocp-hub
 neighbor 192.168.4.117 peer-group ocp-hub
 neighbor 192.168.4.118 peer-group ocp-hub
 neighbor 192.168.4.127 peer-group ocp-hub
 neighbor 192.168.4.135 peer-group ocp-hub
 neighbor 192.168.4.143 peer-group ocp-hub
 neighbor 192.168.4.145 peer-group ocp-hub
 neighbor 192.168.4.177 peer-group ocp-hub
 neighbor 192.168.4.178 peer-group ocp-hub
 !
 address-family ipv4 unicast
  ! annex network connected on br254
  network 10.254.254.0/24
  neighbor ocp-hub activate
  neighbor ocp-hub soft-reconfiguration inbound
  neighbor ocp-hub route-map from-ocp-hub in
  neighbor ocp-hub route-map to-ocp-hub out
 exit-address-family
exit
!
route-map from-ocp-hub permit 10
 match ip address prefix-list from-ocp-hub
exit
!
route-map to-ocp-hub permit 10
 match ip address prefix-list to-ocp-hub
exit
!
end

