---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      demo: rhone-26
      app.kubernetes.io/instance: demo-rhone-26

components:
  - ../../components/br-vmdata
  - ../../components/physnet-mapping

  # add appropriate localnets in overlay
  # - ../../components/localnet-1924

